### ISSUE TITLE
Tagging @everyone

### ISSUE THREAD

**Issue by lolSam** [NNTin/discord-twitter-bot#5]
Hey,

Would it be possible to have the bot tag @everyone when it posts?

Cheers,
Sam

**Comment by NNTin** [comment]
main.py, line 63, replace:  
`wh = Webhook(url=wh_url)` 
with: 
`wh = Webhook(url=wh_url, content='@everyone')`

I personally don't like it because it makes the text formatting look a lot worse. And people who don't care are then forced to mute the channel. If you have a dedicated text channel it's better if the users enable notification themselves.  
![image](https://user-images.githubusercontent.com/18033169/28965290-957c7b3c-7910-11e7-9043-1d053f8a489f.png)
